version: '3.4'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      #target: debug
    ports:
      - "5000:5000"
      - "8080:80"
    volumes:
      - .:/app
    environment:
      FLASK_APP: /app/app.py
      SECRETS_FILE: /app/app/instance/client_secrets.json
      CREDENTIALS_FILE: /app/app/instance/credentials.json
      DATABASE_URL: sqlite:////app/app.db      
      #FLASK_ENV: development
    command: flask run --host 0.0.0.0 --port=5000 
    
    
